sync_address = "https://atuin.edgard.org"
sync_frequency = "10m"
dialect = "uk"
auto_sync = true
update_check = false
enter_accept = false
style = "auto"
inline_height = 14
inline_height_shell_up_key_binding = 1
show_help = false
filter_mode_shell_up_key_binding = "session"
show_preview = false
search_mode = "fulltext"
search_mode_shell_up_key_binding = "fulltext"
show_tabs = false
secrets_filter = false

[keys]
scroll_exits = false

[sync]
records = true

[theme]
name = "catppuccin-frappe-mauve"
