approval_policy = "never"
sandbox_mode = "danger-full-access"
check_for_update_on_startup = false

[mcp_servers.context7]
url = "https://mcp.context7.com/mcp"
env_http_headers = { CONTEXT7_API_KEY = "CONTEXT7_API_KEY" }

[mcp_servers.grep]
url = "https://mcp.grep.app"

[mcp_servers.exa]
url = "https://mcp.exa.ai/mcp"
