model = "gpt-5.2-codex"
model_reasoning_effort = "xhigh"
model_verbosity = "medium"
approval_policy = "never"
sandbox_mode = "danger-full-access"
file_opener = "vscode"

[features]
apply_patch_freeform = true
streamable_shell = true
web_search_request = true
rmcp_client = true

[notice.model_migrations]
"gpt-5.1-codex-max" = "gpt-5.2-codex"
